//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavileniDB.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.Tenants1 = new HashSet<Tenants>();
        }
    
        public int IdRent { get; set; }
        public Nullable<int> IdTancent { get; set; }
        public string NameShopMall { get; set; }
        public Nullable<int> IdEmploye { get; set; }
        public string NumberPav { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OpenRent { get; set; }
        public Nullable<System.DateTime> CloseRent { get; set; }
    
        public virtual Pavilieni Pavilieni { get; set; }
        public virtual ShoppingMall ShoppingMall { get; set; }
        public virtual Tenants Tenants { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenants> Tenants1 { get; set; }
    }
}
